### PR TITLE
Updated paper title and conference name

### PR DESCRIPTION
**Pull request by zkytony**
Learning Graph-Structured Sum-Product Networks for Probabilistic Semantic Maps appeared in AAAI 2018

### CODE REVIEW

**Comment by arranger1044** [comment]
Thanks!
I was on that myself, but you arrived first. Before merging, could you please update the other references in the 'Models' and 'References' section?

**Comment by arranger1044** [comment]
Thanks, very appreciated

**Comment by zkytony** [comment]
Why is this closed without being merged? @arranger1044

**Comment by arranger1044** [comment]
Sorry my bad!

**Pull request merged**
