### PR TITLE
added citation..

### PR DESCRIPTION
**Pull request by trappmartin**
added: 

Trapp M., Peharz R., Skowron M., Madl T., Pernkopf F. and Trappl R.: 
Structure Inference in Sum-Product Networks using Infinite Sum-Product Trees. 
Practical Bayesian Nonparametrics Workshop at NIPS, 2016.

### CODE REVIEW

**Review by arranger1044 — CHANGES_REQUESTED** [review]
i) An entry shall be added to the 'Structure Learning' topic category, with some additional labels (can something like 'infinite SPT' be alright?)

ii) is the provided drive link a stable one?

**Comment by arranger1044** [comment]
Thanks @trappmartin very appreciated!
This seems a very interesting bayesian approach to structure learning
Before merging could you also please add the same entry to the structure learning sub-topic?

**Comment by trappmartin** [comment]
The structure learning sub-topic entry should be there now. The link refers to the pdf provided by the workshop organizers. So it should be stable. I can add the pdf to our institute server and link to this file if you encounter any difficulties.

**Comment by arranger1044** [comment]
Thanks Martin, nicely done!
Sorry for the bother, maybe there is a better way to manage this redundancy of information in a single markdown

**Pull request merged**
